---
  config:
    layout: elk
    theme: neutral
    class:
      hideEmptyMembersBox: true
---

classDiagram
    namespace YAAIR {
        class Engine { }
        class Network {
            <<interface>>
        }
        class AggregateProgram {  }
    }

    class ZenohNetwork { }

    class ZenohConfigBuilder { }

    class ZenohConfig { }

    Engine *-- AggregateProgram : requires
    Engine *-- Network : requires
    Network <|.. ZenohNetwork : implements
    ZenohNetwork --> ZenohConfig : configured by
    ZenohConfigBuilder ..> ZenohConfig : creates
